FROM kerneltime/rust

MAINTAINER Ritesh H Shukla <kerneltime@gmail.com>

RUN set -ex

RUN git clone https://github.com/phildawes/racer.git /root/src/racer
RUN cd /root/src/racer; cargo build --release

RUN mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

RUN git clone --depth=1 https://github.com/rust-lang/rust.vim.git ~/.vim/bundle/rust.vim

RUN git clone https://github.com/racer-rust/vim-racer.git ~/.vim/bundle/vim-racer && \
	mkdir -p ~/.vim/plugin && \
	cp ~/.vim/bundle/vim-racer/plugin/racer.vim ~/.vim/plugin 
 
RUN git clone https://github.com/jlanzarotta/bufexplorer.git ~/.vim/bundle/bufexplorer 

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y  zsh

RUN git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh && \
	cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc 

RUN git clone http://github.com/sjl/gundo.vim.git ~/.vim/bundle/gundo

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y silversearcher-ag && \
        git clone https://github.com/rking/ag.vim.git ~/.vim/bundle/ag.vim

RUN git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline

# http://ctrlpvim.github.io/ctrlp.vim
RUN git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y rlwrap apt-transport-https

COPY docker.list /etc/apt/sources.list.d/docker.list
RUN DEBIAN_FRONTEND=noninteractive apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
	DEBIAN_FRONTEND=noninteractive apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y apparmor



COPY vimrc /root/.vimrc

