FROM ubuntu

MAINTAINER Ritesh H Shukla <kerneltime@gmail.com>

ENV GOPATH=/root/src

RUN set -ex

RUN DEBIAN_FRONTEND=noninteractive apt-get update &&\ 
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	vim vim-scripts vim-gocomplete vim-youcompleteme vim-addon-manager vim-syntax-docker \
	git \
	golang gocode \
	make curl wget python clang llvm gcc g++ cmake libssl-dev \
	ssh

RUN go get golang.org/x/tools/cmd/goimports &&\ 
	go get github.com/golang/lint/golint
