FROM kerneltime/ubuntu-base

MAINTAINER Ritesh H Shukla <kerneltime@gmail.com>

RUN git clone https://github.com/rust-lang/rust.git /root/src/rust

RUN cd /root/src/rust && ./configure && make && make install

RUN git clone https://github.com/rust-lang/cargo.git /root/src/cargo

RUN cd /root/src/cargo && \
    	git submodule update --init && \
	python -B src/etc/install-deps.py && \
	./configure && make && make install

ENV RUST_SRC_PATH=/root/src/rust/src
